### PR TITLE
Cmake build setup for the project (DO NOT MERGE YET)

### PR DESCRIPTION
**Pull request by sirpalee**
Setting up CMake build files for multiple platforms. The PR is still in progress until I can test on all platforms.

Where do you usually put the lens files in the installed plugin directory? I just put them in the lenses subdirectory as of now.

### CODE REVIEW

**Comment by zpelgrims** [comment]
Hey man! Thanks for these changes. Why can I not merge this yet? Let me know when I can :)

**Comment by sirpalee** [comment]
Hey, because I haven't had the time to make the cmake setup to work on windows and osx. I'm planning to finish that up quickly, once I can find the time to boot up a windows at home and setup a dev environment there.

**Comment by sirpalee** [comment]
Hey!

Sorry, I completely forgot about this PR. Let me run some tests on windows and get this thing up and running.

**Comment by zpelgrims** [comment]
Hey man - I’ve abandoned this project for POTA instead. It’s much faster and robust.

**Comment by sirpalee** [comment]
Gotcha!

I was just looking at adding POTA to our pipe. :) I'm closing the PR then.

**Comment by zpelgrims** [comment]
That's awesome. Let me know if you've got any questions.

**Pull request closed without merging**
